version: '3.4'
services:
  nodeserver:
    build: .
    container_name: "springapp"
    ports:
      - 8880:8080
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - mongo-data:/var/data
    container_name: "mongodb-service"
    ports:
     - 27017:27017
volumes:
  mongo-data:
